#ifndef APP_CONFIG_H_INCLUDED
#define APP_CONFIG_H_INCLUDED

/*
 *  Macro riguardanti la configurazione dell'applicazione
 */

#define APP_CONFIG_FIRMWARE_VERSION_MAJOR 0UL
#define APP_CONFIG_FIRMWARE_VERSION_MINOR 2UL
#define APP_CONFIG_FIRMWARE_VERSION_PATCH 0UL

#define APP_CONFIG_TASK_SIZE 512

#define APP_CONFIG_PASSWORD "72346"

#define APP_CONFIG_MIN_LIMITE_TEMPERATURA     100
#define APP_CONFIG_DEFAULT_LIMITE_TEMPERATURA 100
#define APP_CONFIG_MAX_LIMITE_TEMPERATURA     150

#endif
